[build]
command = "rm -rf .next node_modules/.cache && npx next build"
publish = ".next"

[functions."process-import"]
background = true

[functions."process-import-background"]
background = true

[functions."publish-scheduled"]
schedule = "*/5 * * * *"

[[plugins]]
package = "@netlify/plugin-nextjs"
