export { EDITORIAL_IDENTITY, EDITORIAL_CHARTER, EDITORIAL_STYLE_INSTRUCTION, EDITORIAL_FORBIDDEN_PHRASES, EDITORIAL_LEVELS, EDITORIAL_FINAL_CHECKS, SYSTEM_PROMPT } from './editorial/editorial-style';
